### ISSUE TITLE
Feedback and Feature suggestions

### ISSUE THREAD

**Issue by ozmutley** [Makin-Things/makin-things-weather-card#4]
I posted in the forum before finding this repository so apologies for the double posting.

I’m currently trying out the new Alpha release and liking it so far - especially the GUI config. Makes things easier to quickly move entities around without having to edit the YAML

I did come across two changes I had to make to the template sensors within the _weather.yaml_ file from DavidFW1960's repository (unsure if you are including these templates with the new version card). The alternate code for the **bom_today_max** and **bom_today_min** template sensors needed to have their comparison values changed from **'n/a'** to **'unknown'** as that was the value that the BoM integration was returning for missing forecasted temps - so my code block now reads -
```
     bom_today_max:
        value_template: >
          {%- if states('sensor.cardiff_temp_max_0') == 'unknown' -%} 
            {{ state_attr('sensor.today_temp_bom', 'max_value') }}
          {% else %}
            {{ states('sensor.cardiff_temp_max_0') }}
          {% endif %}
```

I also came up with a couple of suggestions that I'm hoping could be considered:

- It would be nice if the card could be made actionable like other Lovelace cards ? My idea was to have a ‘summary’ card showing some weather details but either going to a pop-up or navigating to another view with more detailed information when the card is tapped, double-tapped, or tapped and held.

- Maybe not 'need to have' but 'nice to have' would be the ability to input templates into the entity fields. An immediate thought would be for the 'Forecast Possible' field where some weather integrations may provide separate min and max rain forecast entities and thus being able to join those together into a single string using a template

**Comment by DavidFW1960** [comment]
> The alternate code for the **bom_today_max** and **bom_today_min** template sensors needed to have their comparison values changed from **'n/a'** to **'unknown'**

Did you log that as an issue for the card?

**Comment by Makin-Things** [comment]
> 

I don't believe this is an issue the card can solve. The sensor itself (ie. the input to the template) is set to unknown. This happens when the bom doesn't publish data for the field. This all happens before the template sensor gets passed to the card.

**Comment by Makin-Things** [comment]
@ozmutley for the feature ideas, the first one may happen at some point, but not in the near future. The second one I am not even going to consider. You are far better creating a template sensor in ha and then just use it. I see no real benefit for the massive amount of work this would take (and likely to get broken often when the ha devs change things).

**Comment by ozmutley** [comment]
> > The alternate code for the **bom_today_max** and **bom_today_min** template sensors needed to have their comparison values changed from **'n/a'** to **'unknown'**
> 
> Did you log that as an issue for the card?

@DavidFW1960 - I thought I had created an issue under the card but going back and looking it appears that it did not get submitted to github. I have created an issue under the original card.

**Comment by ozmutley** [comment]
> @ozmutley for the feature ideas, the first one may happen at some point, but not in the near future. The second one I am not even going to consider. You are far better creating a template sensor in ha and then just use it. I see no real benefit for the massive amount of work this would take (and likely to get broken often when the ha devs change things).

@Makin-Things - Thanks for the reply. After reading your comments about the 2nd item I'm happy for you throw out that idea. 

The first item is something I think would be of benefit to the card sometime in the future so I will look forward to when it is able to be implemented.

Thanks for the time and effort both of you are putting into creating this awesome card - it is appreciated.
