### ISSUE TITLE
[Bug] - Overview Section - Current Text - Optional

### ISSUE THREAD

**Issue by kingy444** [Makin-Things/makin-things-weather-card#6]
**Is your feature request related to a problem? Please describe.**
I dont have a need to display the short text on card when i am already displaying extended text.

**Describe the solution you'd like**
I would like the short description to be optional, and if not present the text shifts up such as below.
This was achieved with some dom manipulation in chrome - and adding 'padding-top: 0px; to .extended-section

Current
![image](https://user-images.githubusercontent.com/7148670/175920595-3c27f79f-e897-47e7-94ce-5ed50cd82a0a.png)

Desired
![image](https://user-images.githubusercontent.com/7148670/175920804-3adc2e33-460f-427f-8b7f-02e2bd9f9f7c.png)

**Describe alternatives you've considered**
Using card-mod

**Comment by Makin-Things** [comment]
This should have been the case already. The intention was that if you didn't choose an entity for it the field should vanish. Look for an update tomorrow.
From the forecast it look like you are also in Canberra.

**Comment by kingy444** [comment]
That i am - does that mean you are too or you just know how cold it can be here ? 🤣

**Comment by Makin-Things** [comment]
I am in Canberra and the forecast in the images you posted was identical.
It will take me about 5-10 minutes to fix it tomorrow.

**Comment by Makin-Things** [comment]
I have pushed a fix. If you don't provide an entity nothing will be displayed now.
